language: cpp
script:
  - sh tools/get_pthsem
  - sh -x bootstrap.sh
  - env CFLAGS="-Wall -Wextra" CPPFLAGS="-Wall -Wextra" ./configure --with-pth=$HOME/pthsem --without-pth-test --disable-systemd
  - make
  - env LD_LIBRARY_PATH=$HOME/pthsem/lib sh tools/test.sh
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
    - $HOME/pthsem
sudo: false
